services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: authuser
      POSTGRES_PASSWORD: authpass
      POSTGRES_DB: authdb
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U authuser -d authdb"]
      interval: 5s
      timeout: 3s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://db:5432/authdb
      QUARKUS_DATASOURCE_USERNAME: authuser
      QUARKUS_DATASOURCE_PASSWORD: authpass
      MP_JWT_VERIFY_ISSUER: auth-rbac-quarkus
    ports:
      - "8080:8080"

volumes:
  pgdata:
