FROM eclipse-temurin:21-jre
WORKDIR /app
COPY target/*-runer.jar /app/app.jar
EXPOSE 8080
# Variáveis injetáveis em prod
ENV QUARKUS_HTTP_PORT=8080 \
    DB_USER=authuser \
    DB_PASS=authpass \
    DB_NAME=authdb \
    JWT_ISSUER=auth-rbac-quarkus
CMD ["java","-jar","/app/app.jar"]
